print("Welcome to the tip calculator")
bill = input("What was the total bill?  $" )
bill_to_float = float(bill)
procent = input("What percentage tip would you like to give? 10,12, 15? ")
procent_to_int=int(procent)
people = input ("How many people to split the bill? ")
people_to_int=int(people)
result = (((bill_to_float + (bill_to_float * procent_to_int/100))/people_to_int))
print(f"Each person should pay: ${round(result,2)}")